config/routes.rb
Air::Application.routes.draw do

  get "/sessions/new" => 'Sessions#new', as: 'new_session'
  post "/sessions" => "Sessions#create", as: 'sessions'
  delete "/sessions" => "Sessions#destroy"

  post '/flights/search' => 'flights#index'

  resources :airports

  resources :reservations

  resources :users

  resources :flights

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :arrival_airport_id, :departs_at, :departure_airport_id, :flight_num, :seats

  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'

  has_many :reservations

  MILEAGE_HASH = {'JFK - ORD' => 740,
                  'LAX - ORD' => 1744,
                  'ORD - SFO' => 1846,
                  'JFK - LAX' => 2475,
                  'JFK - SFO' => 2586,
                  'LAX - SFO' => 338 }

  def miles
    flight_path_array = [arrival_airport.code, departure_airport.code]
    flight_path_array.sort!
    flight_path = "#{flight_path_array[0]} - #{flight_path_array[1]}"
    Flight::MILEAGE_HASH[flight_path]
  end

  def duration_in_minutes
    return self.miles/8
  end

  def arrives_at
    return self.departs_at + (self.duration_in_minutes * 60)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # GET /flights
  # GET /flights.json
  def index
    if params[:search]
      airport = Airport.where("code LIKE ? OR city LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").first
      if airport
        @flights = Flight.where("arrival_airport_id == ? OR departure_airport_id == ? ", "#{airport.id}", "#{airport.id}")
      else
        @flights = Flight.all
      end
    else
      @flights = Flight.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flights }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/new
  # GET /flights/new.json
  def new
    @flight = Flight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find(params[:id])
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(params[:flight])

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render json: @flight, status: :created, location: @flight }
      else
        format.html { render action: "new" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flights/1
  # PUT /flights/1.json
  def update
    @flight = Flight.find(params[:id])

    respond_to do |format|
      if @flight.update_attributes(params[:flight])
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_num %><br />
    <%= f.number_field :flight_num %>
  </div>
  <div class="field">
    <%= f.label :departs_at %><br />
    <%= f.time_select :departs_at %>
  </div>
  <div class="field">
    <%= f.label :seats %><br />
    <%= f.number_field :seats %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :arrival_airport_id %><br />
    <%= f.number_field :arrival_airport_id %>
  </div>
  <div class="field">
    <%= f.label :departure_airport_id %><br />
    <%= f.number_field :departure_airport_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="span12">
        <h1 class="page-header">Today's Flight Schedule</h1>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Flight #</th>
              <th>From</th>
              <th>Departs</th>
              <th>To</th>
              <th>Arrives</th>
              <th>Miles</th>
              <th>Duration</th>
              <th>Seats</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @flights.each do |flight| %>
              <tr>
                <td><%= flight.flight_num %></td>
                <td><%= flight.departure_airport.code %></td>
                <td><%= flight.departs_at.strftime "%1:%M %p" %></td>
                <td><%= flight.arrival_airport.code %></td>
                <td><%= flight.arrives_at.strftime "%1:%M %p" %></td>
                <td><%= flight.miles %></td>
                <td><%= flight.duration_in_minutes %> minutes</td>
                <td><%= flight.seats %></td>
                <td>
                    <!--<a href="/reservations/new?flight_id=5" class="btn btn-success">Book Now</a>-->
                    <%= link_to "Book Now", new_reservation_url({ flight_id: 5 }), class: 'btn btn-success' %>
                </td>
              </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </div>

    <hr>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Flight num:</b>
  <%= @flight.flight_num %>
</p>

<p>
  <b>Departs at:</b>
  <%= @flight.departs_at %>
</p>

<p>
  <b>Seats:</b>
  <%= @flight.seats %>
</p>

<p>
  <b>Created at:</b>
  <%= @flight.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @flight.updated_at %>
</p>

<p>
  <b>Arrival airport:</b>
  <%= @flight.arrival_airport_id %>
</p>

<p>
  <b>Departure airport:</b>
  <%= @flight.departure_airport_id %>
</p>


<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>