config/routes.rb
Air::Application.routes.draw do

  get "/sessions/new" => 'Sessions#new', as: 'new_session'
  post "/sessions" => "Sessions#create", as: 'sessions'
  delete "/sessions" => "Sessions#destroy"

  post '/flights/search' => 'flights#index'

  resources :airports

  resources :reservations

  resources :users

  resources :flights

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  attr_accessible :city, :code, :created_at, :updated_at

  has_many :flights

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @airports }
    end
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
    @airport = Airport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @airport }
    end
  end

  # GET /airports/new
  # GET /airports/new.json
  def new
    @airport = Airport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @airport }
    end
  end

  # GET /airports/1/edit
  def edit
    @airport = Airport.find(params[:id])
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(params[:airport])

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render json: @airport, status: :created, location: @airport }
      else
        format.html { render action: "new" }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /airports/1
  # PUT /airports/1.json
  def update
    @airport = Airport.find(params[:id])

    respond_to do |format|
      if @airport.update_attributes(params[:airport])
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport = Airport.find(params[:id])
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to airports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<h1>Listing airports</h1>

<table>
  <tr>
    <th>City</th>
    <th>Code</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airports.each do |airport| %>
  <tr>
    <td><%= airport.city %></td>
    <td><%= airport.code %></td>
    <td><%= airport.created_at %></td>
    <td><%= airport.updated_at %></td>
    <td><%= link_to 'Show', airport %></td>
    <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
    <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Airport', new_airport_path %>

app/views/airports/new.html.erb
<h1>New airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @airport.city %>
</p>

<p>
  <b>Code:</b>
  <%= @airport.code %>
</p>

<p>
  <b>Created at:</b>
  <%= @airport.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @airport.updated_at %>
</p>


<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>