config/routes.rb
Air::Application.routes.draw do

  get "/sessions/new" => 'Sessions#new', as: 'new_session'
  post "/sessions" => "Sessions#create", as: 'sessions'
  delete "/sessions" => "Sessions#destroy"

  post '/flights/search' => 'flights#index'

  resources :airports

  resources :reservations

  resources :users

  resources :flights

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneWayAir</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <title>OneWay Airlines</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <!-- <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet"> -->

    <link rel="stylesheet" type="text/css" href="http://bootswatch.com/united/bootstrap.min.css">
    <style type="text/css">
      body { padding-top: 60px; padding-bottom: 40px; }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <style type="text/css">
      .table thead th { font-size: 20px; background: #5484a7; color: white; text-align: center; height: 30px; padding: 12px; vertical-align: middle}
      .table td { text-align: center; }
    </style>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-114x114.png">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand span2" href="/">OneWay Airlines</a>
        <div class="nav-collapse">
          <!-- <form class="navbar-search pull-left" action="/flights"> -->
          <%= form_tag(flights_url, class: 'navbar-search pull-left', method: 'get') do %>
            <%= text_field_tag :search, nil, placeholder: "Search by city or airport code", class: 'search-query span3'  %>
            <!-- <input type="text" class="search-query span3" placeholder="Search by city or airport code"> -->
          <% end %>
          <!-- </form> -->
          <ul class="nav pull-right">
            <li><a href="/airports.html">Cities</a></li>
            <li><a href="/support.html">Customer Support</a></li>
            <li><a href="/profile.html">My Profile</a></li>
            <li>
              <% if session[:user_id].present? %>
                <%= link_to "Logout", sessions_url, method: 'delete' %>
              <% else %>
                <%= link_to "Sign In", new_session_url %>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

<%= yield %>

  <footer>
    <p>&copy;2013 OneWay Airlines.  Got a comment or suggestion?  Keep it to yourself!</p>
  </footer>

</body>
</html>